#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : lshw
Version  : 02.19.2
Release  : 8
URL      : https://www.ezix.org/software/files/lshw-B.02.19.2.tar.gz
Source0  : https://www.ezix.org/software/files/lshw-B.02.19.2.tar.gz
Summary  : HardWare LiSter
Group    : Development/Tools
License  : GPL-2.0
Requires: lshw-bin = %{version}-%{release}
Requires: lshw-data = %{version}-%{release}
Requires: lshw-license = %{version}-%{release}
Requires: lshw-locales = %{version}-%{release}
Requires: lshw-man = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0002-fix-locale-file-mode.patch

%description
lshw (Hardware Lister) is a small tool to provide detailed information on
the hardware configuration of the machine. It can report exact memory
configuration, firmware version, mainboard configuration, CPU version
and speed, cache configuration, bus speed, etc. on DMI-capable x86s
systems and on some PowerPC machines (PowerMac G4 is known to work).

Information can be output in plain text, XML or HTML.

For detailed information on lshw features and usage, please see the
included documentation or go to the lshw Web page,
http://lshw.ezix.org/

%package bin
Summary: bin components for the lshw package.
Group: Binaries
Requires: lshw-data = %{version}-%{release}
Requires: lshw-license = %{version}-%{release}

%description bin
bin components for the lshw package.


%package data
Summary: data components for the lshw package.
Group: Data

%description data
data components for the lshw package.


%package license
Summary: license components for the lshw package.
Group: Default

%description license
license components for the lshw package.


%package locales
Summary: locales components for the lshw package.
Group: Default

%description locales
locales components for the lshw package.


%package man
Summary: man components for the lshw package.
Group: Default

%description man
man components for the lshw package.


%prep
%setup -q -n lshw-B.02.19.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1679612623
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1679612623
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lshw
cp %{_builddir}/lshw-B.%{version}/COPYING %{buildroot}/usr/share/package-licenses/lshw/4cc77b90af91e615a64ae04893fdffa7939db84c || :
%make_install
%find_lang lshw

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lshw

%files data
%defattr(-,root,root,-)
/usr/share/lshw/manuf.txt
/usr/share/lshw/oui.txt
/usr/share/lshw/pci.ids
/usr/share/lshw/pnp.ids
/usr/share/lshw/pnpid.txt
/usr/share/lshw/usb.ids

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lshw/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/lshw.1

%files locales -f lshw.lang
%defattr(-,root,root,-)

